package com.company.model.enums;

/**
 * The base type possible for a unit.
 * This goes <i>over</i> a tile
 */
public enum UnitType {
	// Markers
	PLUNDER1,
	PLUNDER2,
	PLUNDER3,
	PLUNDER4,
	END_TURN,

	// Feudal units
	FEUDAL_C_RANK,
	FEUDAL_C_RANK_ZOOM,
	FEUDAL_B_RANK,
	FEUDAL_B_RANK_ZOOM,
	FEUDAL_B_RANK_2,
	FEUDAL_B_RANK_2_ZOOM,
	FEUDAL_A_RANK,
	FEUDAL_A_RANK_ZOOM,
	FEUDAL_A_RANK_2,
	FEUDAL_A_RANK_2_ZOOM,
	FEUDAL_A_RANK_3,
	FEUDAL_A_RANK_3_ZOOM,
	JOHN_GORDON,
	JOHN_GORDON_ZOOM,
	ROBERT_KEITH,
	ROBERT_KEITH_ZOOM,
	THOPMAS_BRUCE,
	THOPMAS_BRUCE_ZOOM,
	FRIAR_SIMON,
	FRIAR_SIMON_ZOOM,
	SIR_RANDOLPH,
	SIR_RANDOLPH_ZOOM,
	SIR_GODFREY,
	SIR_GODFREY_ZOOM,
	SIR_HILBERT,
	SIR_HILBERT_ZOOM,
	COUNT,
	COUNT_ZOOM,
	BARON,
	BARON_ZOOM,

	// Goblin units
	GOBLIN_C_RANK,
	GOBLIN_C_RANK_ZOOM,
	GOBLIN_C_RANK_2,
	GOBLIN_C_RANK_2_ZOOM,
	GOBLIN_B_RANK,
	GOBLIN_B_RANK_ZOOM,
	GOBLIN_B_RANK_2,
	GOBLIN_B_RANK_2_ZOOM,
	PHINLOC,
	PHINLOC_ZOOM,
	UGLOP,
	UGLOP_ZOOM,
	GRINPHAR,
	GRINPHAR_ZOOM,
	KASBOSH,
	KASBOSH_ZOOM,
	ARGBARG,
	ARGBARG_ZOOM,
	MARGLUSH,
	MARGLUSH_ZOOM,
	KING,
	KING_ZOOM,

	// Blank sprite
	EMPTY_UNIT,

	// Special tilename for testing purpose
	AA, AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL, AM, AN, AO, AP, AQ, AR, AS, AT, AU, AV, AW, AX, AY, AZ,
	BA, BB, BC, BD, BE, BF, BG, BH, BI, BJ, BK, BL, BM, BN, BO, BP, BQ, BR, BS, BT, BU, BV, BW, BX, BY, BZ,
	CA, CB, CC, CD, CE, CF, CG, CH, CI, CJ, CK, CL, CM, CN, CO, CP, CQ, CR, CS, CT, CU, CV, CW, CX, CY, CZ
}
